service: civicforge-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  
  httpApi:
    throttle:
      rateLimit: 100  # requests per second
      burstLimit: 200  # burst capacity
  
  environment:
    COGNITO_REGION: ${self:provider.region}
    COGNITO_USER_POOL_ID: ${ssm:/civicforge/${self:provider.stage}/cognito-user-pool-id}
    COGNITO_APP_CLIENT_ID: ${ssm:/civicforge/${self:provider.stage}/cognito-app-client-id}
    USERS_TABLE: ${self:custom.usersTable}
    QUESTS_TABLE: ${self:custom.questsTable}
    FAILED_REWARDS_TABLE: ${self:custom.failedRewardsTable}
    FRONTEND_URL: ${ssm:/civicforge/${self:provider.stage}/frontend-url, 'http://localhost:5173'}
    # Feature flags
    FF_REWARD_DISTRIBUTION: ${env:FF_REWARD_DISTRIBUTION, 'false'}
    FF_SIGNATURE_ATTESTATION: ${env:FF_SIGNATURE_ATTESTATION, 'true'}
    FF_DISPUTE_RESOLUTION: ${env:FF_DISPUTE_RESOLUTION, 'false'}
  
  iam:
    role:
      statements:
        # Minimal default permissions for logging
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:${self:provider.region}:${aws:accountId}:log-group:/aws/lambda/${self:service}-${self:provider.stage}-*:*"

custom:
  usersTable: civicforge-${self:provider.stage}-users
  questsTable: civicforge-${self:provider.stage}-quests
  failedRewardsTable: civicforge-${self:provider.stage}-failed-rewards
  pythonRequirements:
    dockerizePip: true
    slim: true
  serverless-offline:
    httpPort: 3001

functions:
  # Main API handler - handles most operations except critical ones
  api:
    handler: handlers.api.handler
    events:
      # Health check and general routes
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /api/v1/quests
          method: GET
      - httpApi:
          path: /api/v1/quests/{quest_id}
          method: GET
      - httpApi:
          path: /api/v1/quests/{quest_id}/claim
          method: POST
      - httpApi:
          path: /api/v1/quests/{quest_id}/submit
          method: POST
      - httpApi:
          path: /api/v1/quests/{quest_id}/dispute
          method: POST
      - httpApi:
          path: /api/v1/users/{user_id}
          method: GET
      - httpApi:
          path: /api/v1/users/wallet
          method: PUT
      - httpApi:
          path: /api/v1/feature-flags
          method: GET
    iamRoleStatements:
      # Read permissions
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}/index/*"
      # Update permissions for quest operations
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
      # Restricted UpdateItem on UsersTable - only allow wallet address updates
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
        Condition:
          ForAllValues:StringEquals:
            "dynamodb:Attributes":
              - "walletAddress"
              - "updatedAt"
      # Explicitly DENY dangerous operations
      - Effect: Deny
        Action:
          - dynamodb:DeleteItem
        Resource: "*"
  
  # Critical operation: Create Quest (involves financial transaction)
  createQuest:
    handler: handlers.create_quest.handler
    events:
      - httpApi:
          path: /api/v1/quests
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
      # Restricted UpdateItem on UsersTable - only allow quest creation point deduction
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
        Condition:
          ForAllValues:StringEquals:
            "dynamodb:Attributes":
              - "questCreationPoints"
              - "updatedAt"
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
  
  # Critical operation: Attest Quest (involves rewards)
  attestQuest:
    handler: handlers.attest_quest.handler
    events:
      - httpApi:
          path: /api/v1/quests/{quest_id}/attest
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
      # Separate GetItem for UsersTable (no attribute restriction needed for reads)
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
      # Restricted UpdateItem on UsersTable - only allow specific attributes
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
        Condition:
          ForAllValues:StringEquals:
            "dynamodb:Attributes":
              - "xp"
              - "reputation"
              - "questCreationPoints"
              - "processedRewardIds"
              - "updatedAt"
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.failedRewardsTable}"
  
  # Critical operation: Delete Quest (dangerous operation)
  deleteQuest:
    handler: handlers.delete_quest.handler
    events:
      - httpApi:
          path: /api/v1/quests/{quest_id}
          method: DELETE
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.questsTable}"
      # Restricted UpdateItem on UsersTable - only allow quest point refund
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
        Condition:
          ForAllValues:StringEquals:
            "dynamodb:Attributes":
              - "questCreationPoints"
              - "updatedAt"
  
  createUserTrigger:
    handler: src.triggers.create_user.handler
    memorySize: 128
    timeout: 10
    environment:
      USERS_TABLE_NAME: ${self:custom.usersTable}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.usersTable}"
    onError: !GetAtt UserCreationDLQ.Arn
  
  # DLQ Re-processor for failed rewards
  reprocessFailedRewards:
    handler: src.triggers.reprocess_failed_rewards.handler
    memorySize: 256
    timeout: 60
    events:
      # Run every 15 minutes
      - schedule: rate(15 minutes)
    environment:
      USERS_TABLE: ${self:custom.usersTable}
      FAILED_REWARDS_TABLE: ${self:custom.failedRewardsTable}
      MAX_RETRY_ATTEMPTS: 5
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.failedRewardsTable}"
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.failedRewardsTable}/index/status-createdAt-index"
      # Read access to Users table
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
      # Restricted UpdateItem on UsersTable - only allow specific attributes
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTable}"
        Condition:
          ForAllValues:StringEquals:
            "dynamodb:Attributes":
              - "xp"
              - "reputation"
              - "questCreationPoints"
              - "processedRewardIds"
              - "updatedAt"

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-iam-roles-per-function

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    
    QuestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.questsTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: questId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: creatorId
            AttributeType: S
          - AttributeName: performerId
            AttributeType: S
        KeySchema:
          - AttributeName: questId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: CreatorIndex
            KeySchema:
              - AttributeName: creatorId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: PerformerIndex
            KeySchema:
              - AttributeName: performerId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    
    FailedRewardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.failedRewardsTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: failureId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: failureId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: status-createdAt-index
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    
    # Dead Letter Queue for failed user creation attempts
    UserCreationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-user-creation-dlq
        MessageRetentionPeriod: 1209600  # 14 days
        VisibilityTimeout: 60
    
    # CloudWatch Alarm for DLQ monitoring
    UserCreationDLQAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-user-creation-failures
        AlarmDescription: "Alert when user creation Lambda failures are queued in DLQ"
        MetricName: ApproximateNumberOfMessagesVisible
        Namespace: AWS/SQS
        Statistic: Sum
        Period: 300  # 5 minutes
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - Name: QueueName
            Value: !GetAtt UserCreationDLQ.QueueName
        TreatMissingData: notBreaching
    
    # Lambda permission for Cognito to invoke the trigger
    CreateUserTriggerLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt CreateUserTriggerLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: "arn:aws:cognito-idp:${self:provider.region}:${aws:accountId}:userpool/${ssm:/civicforge/${self:provider.stage}/cognito-user-pool-id}"
    
    # API Error Monitoring - Critical for production readiness
    ApiLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-api
        RetentionInDays: 30
    
    ApiErrorMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: !Ref ApiLogGroup
        FilterPattern: '{ $.level = "ERROR" }'
        MetricTransformations:
          - MetricName: ApiErrors
            MetricNamespace: CivicForge/${self:provider.stage}
            MetricValue: 1
            DefaultValue: 0
    
    ApiErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-api-errors
        AlarmDescription: "Alert when API error rate exceeds threshold"
        MetricName: ApiErrors
        Namespace: CivicForge/${self:provider.stage}
        Statistic: Sum
        Period: 300  # 5 minutes
        EvaluationPeriods: 1
        Threshold: 5
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: notBreaching