name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  python-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit
    
    - name: Run pip-audit
      run: |
        cd backend
        pip-audit -r requirements.txt --desc
    
    - name: Upload pip-audit results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pip-audit-results
        path: pip-audit-output.txt

  npm-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run npm audit
      run: |
        cd frontend
        npm audit --audit-level=high
    
    - name: Check for critical vulnerabilities
      run: |
        cd frontend
        npm audit --json | jq '.vulnerabilities | to_entries | map(select(.value.severity == "critical")) | length' > critical_count.txt
        CRITICAL_COUNT=$(cat critical_count.txt)
        if [ "$CRITICAL_COUNT" -gt "0" ]; then
          echo "Found $CRITICAL_COUNT critical vulnerabilities!"
          exit 1
        fi

  dependabot-alerts:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'